CICD(SonarQube): Added SonarQube

diff --git a/.github/workflows/production.yml b/.github/workflows/production.yml
--- a/.github/workflows/production.yml
+++ b/.github/workflows/production.yml
@@ -25,8 +25,9 @@ jobs:
         run: npm run lint
         continue-on-error: false
   test:
-    name: Test and Coverage Check
+    name: Test and Coverage
     runs-on: ubuntu-latest
+    needs: [lint]
     steps:
       - uses: actions/checkout@v3
 
@@ -35,31 +36,43 @@ jobs:
         with:
           node-version: 18.x
           cache: "npm"
-          cache-dependency-path: package-lock.json
-
-      - name: Cache node modules
-        uses: actions/cache@v3
-        id: npm-cache
-        with:
-          path: ~/.npm
-          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: |
-            ${{ runner.os }}-node-
 
       - name: Install dependencies
         run: npm ci
 
-      - name: Run tests with coverage threshold
+      - name: Run tests with coverage
+        run: npm run test:coverage
+
+      # Verify coverage directory exists and show its contents
+      - name: Debug coverage directory
         run: |
-          npm run test:coverage
-          if [ $? -ne 0 ]; then
-            echo "Tests failed or coverage threshold not met"
-            exit 1
-          fi
+          ls -la
+          ls -la coverage || echo "Coverage directory not found"
+
+      # Upload coverage results with error handling
+      - name: Upload coverage results
+        uses: actions/upload-artifact@v3
+        if: always() # Try to upload even if tests fail
+        with:
+          name: coverage-report
+          path: coverage/lcov.info # Specify exact file
+          if-no-files-found: error # Will fail if files not found
+  sonarqube:
+    runs-on: ubuntu-latest
+    needs: [lint, test]
+    steps:
+    - uses: actions/checkout@v4
+      with:
+        # Disabling shallow clones is recommended for improving the relevancy of reporting
+        fetch-depth: 0
+    - name: SonarQube Scan
+      uses: SonarSource/sonarqube-scan-action@v4.2.1 # Ex: v4.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
+      env:
+        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
   deploy:
     name: Deploy
-    needs: test
+    needs: [lint, test, sonarqube]
     runs-on: ubuntu-latest
     permissions:
       id-token: write
